services:
  database:
    restart: always
    environment:
      - DATABASE_WEB_HOSTNAMES=${TRADERX_FQDN:-localhost}
    image: database
    build:
      context: database
      dockerfile: Dockerfile
    working_dir: /database
    expose:
      - 18082
      - 18083
      - 18084
    ports:
      - 18082:18082
      - 18083:18083
      - 18084:18084
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    command: ./run.sh
    networks:
      - localnet
  xtdb:
    image: ghcr.io/xtdb/xtdb-standalone-ea:latest
    pull_policy: always
    expose:
      - 5432
      - 3000
    ports:
      - 18099:5432
      - 18100:3000
    volumes:
      - xtdb-data:/var/lib/xtdb
    networks:
      - localnet
  reference-service:
    restart: always
    build:
      context: reference-service
      dockerfile: Dockerfile
    expose:
      - 18085
    ports:
      - 18085:18085
    environment:
      - XTDB_HOST=xtdb
      - XTDB_PORT=5432
      - WEB_PORT=18085
      - TRADE_FEED_ADDRESS=http://trade-feed:18086
      - PRICE_UPDATE_INTERVAL_MS=10000
    networks:
      - localnet
    depends_on:
      - xtdb
      - trade-feed
    volumes:
      - ./reference-service:/reference-service
  trade-feed:
    restart: always
    image: trade-feed
    build:
      context: trade-feed
      dockerfile: Dockerfile
    working_dir: /trade-feed
    expose:
      - 18086
    ports:
      - 18086:18086
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    command: npm run start
    networks:
      - localnet
  people-service:
    restart: always
    image: people-service
    build:
      context: people-service
      dockerfile: Dockerfile
    working_dir: /people-service
    expose:
      - 18089
    ports:
      - 18089:18089
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    command: /PeopleService.WebApi dotnet run
    networks:
      - localnet
  account-service:
    restart: always
    image: account-service
    build:
      context: account-service
      dockerfile: Dockerfile
    working_dir: /account-service
    expose:
      - 18088
    ports:
      - 18088:18088
    environment:
      - DATABASE_TCP_HOST=database
      - PEOPLE_SERVICE_HOST=people-service
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    command: ./gradlew bootRun
    networks:
      - localnet
    depends_on:
      - database
      - people-service
  position-service:
    restart: always
    image: position-service
    build:
      context: position-service
      dockerfile: Dockerfile
    working_dir: /position-service
    expose:
      - 18090
    ports:
      - 18090:18090
    environment:
      - DATABASE_TCP_HOST=database
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    command: ./gradlew bootRun
    networks:
      - localnet
    depends_on:
      - database
  trade-service:
    restart: always
    image: trade-service
    build:
      context: trade-service
      dockerfile: Dockerfile
    working_dir: /trade-service
    expose:
      - 18092
    ports:
      - 18092:18092
    environment:
      - DATABASE_TCP_HOST=database
      - PEOPLE_SERVICE_HOST=people-service
      - ACCOUNT_SERVICE_HOST=account-service
      - REFERENCE_SERVICE_HOST=reference-service
      - TRADE_FEED_HOST=trade-feed
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    command: ./gradlew bootRun
    networks:
      - localnet
    depends_on:
      - database
      - people-service
      - account-service
      - reference-service
      - trade-feed
  trade-processor:
    restart: always
    image: trade-processor
    build:
      context: trade-processor
      dockerfile: Dockerfile
    working_dir: /trade-processor
    expose:
      - 18091
    ports:
      - 18091:18091
    environment:
      - DATABASE_TCP_HOST=database
      - TRADE_FEED_HOST=trade-feed
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    command: ./gradlew bootRun
    networks:
      - localnet
    depends_on:
      - database
      - trade-feed
  web-front-end-angular:
    restart: always
    image: web-front-end-angular
    build:
      context: web-front-end/angular
      dockerfile: Dockerfile
    working_dir: /web-front-end/angular
    expose:
      - 18093
    ports:
      - 18093:18093
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    command: npm run start
    networks:
      - localnet
    depends_on:
      - database
      - trade-feed
  ingress:
    image: ingress
    build:
      context: ingress
      dockerfile: Dockerfile
      args:
        - NGINX_HOST=${TRADERX_FQDN:-localhost}
    working_dir: /ingress
    expose:
      - 8080
    ports:
      - 8080:8080
    networks:
      - localnet
    depends_on:
      - database
      - trade-feed
      - people-service
      - account-service
      - position-service
      - trade-service
      - trade-processor
      - reference-service
      - web-front-end-angular

networks:
  localnet:
    driver: bridge

volumes:
  xtdb-data:
    driver: local



