apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-front-end-angular
  name: web-front-end-angular
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-front-end-angular
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: web-front-end-angular
    spec:
      containers:
        - image: traderx/web-front-end-angular
          imagePullPolicy: IfNotPresent
          name: web-front-end-angular
          env:
            - name: WEB_FRONT_END_START_MODE
              value: "start-prod"
          ports:
            - containerPort: 18093
              protocol: TCP
          workingDir: /web-front-end/angular
      restartPolicy: Always
